  apiVersion: argo.io/v1alpha1
  kind: Application
  metadata:
    name: arcadia-fhir-api
    namespace: argocd
  spec:
    project: default

    source:
      repoURL: https://github.com/vinaySanda/ArgoXyram.git
      targetRevision: HEAD
      path: dev
    destination:
      server: https://kubernetes.default.svc
      namespace: mynewapp

    syncPolicy:
      syncOptions:
      - CreateNamespace=true

      automated:
        selfHeal: true
        prune: true
