apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-fhir-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: arcadia-fhir-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arcadia-fhir-api
    spec:
      nodeSelector
        eks.amazonaws.com/nodegroup: provisioning-eks-cluster-01_tgw
      containers:
      - image: 498769975733.dkr.ecr.us-east-1.amazonaws.com/arcadia.io/arcadia-fhir-api:20220422-22e824a
        name: arcadia-fhir-api
        ports:
        - containerPort: 8081
      restartPolicy: Always 
