apiVersion: v1
kind: Service
metadata:
  name: arcadia-fhir-api
  labels:
    app.kubernetes.io/name: arcadia-fhir-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30170
  selector:
    app.kubernetes.io/name: arcadia-fhir-api
  type: NodePort
